services:
  bookstack_db:
    image: mariadb:10.11
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD:-root}
      MYSQL_DATABASE: ${DB_DATABASE:-database_database}
      MYSQL_USER: ${DB_USERNAME:-database_username}
      MYSQL_PASSWORD: ${DB_PASSWORD:-database_user_password}
    env_file:
      - .env
    volumes:
      - bookstack_db:/var/lib/mysql
    healthcheck:
      test: ["CMD", "healthcheck.sh", "--connect", "--innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 5

  bookstack:
    build:
      context: .
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=Asia/Jakarta
      - APP_THEME=default
    env_file:
      - .env
    volumes:
      - bookstack_config:/config
    ports:
      - "${PORT:-6875}:80"
    depends_on:
      bookstack_db:
        condition: service_healthy

volumes:
  bookstack_db:
  bookstack_config:
